// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8XLVXum0pjHSQdhKsUbFPYzLEwURRcc',
    appId: '1:128823857797:web:7d6b1d058082f42f860fec',
    messagingSenderId: '128823857797',
    projectId: 'met-mon-vampire',
    authDomain: 'met-mon-vampire.firebaseapp.com',
    storageBucket: 'met-mon-vampire.firebasestorage.app',
    measurementId: 'G-SNBZG7QH7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9UlYp4upQI8uUWZee8ZMP1krPZzoVugw',
    appId: '1:128823857797:android:c8f94c28d993a383860fec',
    messagingSenderId: '128823857797',
    projectId: 'met-mon-vampire',
    storageBucket: 'met-mon-vampire.firebasestorage.app',
  );
}
